import 'package:flutter/material.dart';
import 'package:lucely/theme.dart';

class HomePage extends StatelessWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        backgroundColor: backgroundColor,
        body: ListView(
          children: [
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
            Text("hello"),
          ],
        ));
  }
}
